services:
  - type: web
    name: krishisahayak
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: SESSION_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: krishisahayak-db
          property: connectionString

databases:
  - name: krishisahayak-db
    databaseName: krishisahayak
    user: krishisahayak_user
    plan: free